### ISSUE TITLE
Missing LICENSE file for eu_ES

### ISSUE THREAD

**Issue by Herrie82** [wooorm/dictionaries#1]
Seems this one is missing.

**Comment by Herrie82** [comment]
Thanks for the great repo! 

I've written a bitbake recipe for our LuneOS (Open webOS fork) mobile operating system, so it can be included in our automated build system which is using OpenEmbedded/Yocto. Not sure it will be of any use for you, but thought to let you know :) 

https://github.com/webOS-ports/meta-webos-ports/blob/fido/meta-luneos/recipes-upstreamable/hunspell-dictionaries/hunspell-dictionaries.bb

It is used in our virtual keyboard which uses Maliit, Hunspell & Presage. Let me know in case you have any remarks. I believe I have done everything correctly with regards to licensing etc, just let me know in case you have any remarks.

**Comment by wooorm** [comment]
All dictionaries published here are partially under the same license as their sources, which is often found in each `LICENSE` file. Just ensure you adhere to those licenses!

**Comment by Herrie82** [comment]
Yup did that :) General package is MIT (though I use nothing of your code, except for your conveniently named folders which match our virtual keyboard language codes :) ). For the rest I took one of the licenses for each language and linked to them and we distribute them as well under LICENSE-languagecode_countrycode :) So I think that should be fine :)

**Comment by wooorm** [comment]
I’m not entirely sure, but I’m also not a lawyer!

**Comment by Herrie82** [comment]
Neither am I, but well it should be close enough. In case they want anything further, I can always accommodate :)
