### ISSUE TITLE
el-polyton no space in 'έψ	εύσ'.

### ISSUE THREAD

**Issue by heydojo** [wooorm/dictionaries#12]
I have been attempting to convert these dictionaries to qtwebengine format using qt's qwebengine_convert_dict tool.

I was unable to convert the file **el-polyton/index.bdic** due to the following error:

`Did not find a space in 'έψ	εύσ'.`

Most other dictionaries did build using the tool so it leads me to believe that the fault may be with **el-polyton/index.aff** but as someone who is unfamiliar with hunspell, I am unable to tell if it needs a space instead of the tab.
If so, it seems more useful to report it here than just fix it at my end.

**Comment by wooorm** [comment]
Could you check if the [source dictionary](https://thepolytonicproject.gr/spell/), mentioned in [the readme](https://github.com/wooorm/dictionaries/tree/master/dictionaries/el-polyton), has the same problem?

**Comment by heydojo** [comment]
That's a lot of greek :)
Anyway, replacing the tab with a space using sed works for me here.

`sed -i 's/REP έψ	εύσ/REP έψ εύσ/g' dictionaries/el-polyton/index.aff`

To answer your question; I'd need a link to index.aff and index.dic
https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fthepolytonicproject.gr%2Fspell%2F
I can't see one on the page you linked and I'm not natively Greek :)
Thanks!

**Comment by wooorm** [comment]
You can get the last version from sourceforge, this includes the dic and off files: https://iweb.dl.sourceforge.net/project/greekpolytonicsp/greek_polytonic_2.0.7.oxt

**Comment by wooorm** [comment]
@heydojo Ping!
