### ISSUE TITLE
hu: Word does not match

### ISSUE THREAD

**Issue by heydojo** [wooorm/dictionaries#13]
I have been attempting to convert these dictionaries to qtwebengine format using qt's qwebengine_convert_dict tool.

I was unable to convert the file **hu/index.bdic** due to the following error:

`Word does not match! - Index:    35768 - Expected: gĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłl - Actual:   gĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂłĂl - ERROR converting, the dictionary does not check out OK.`

Most other dictionaries did build using the tool so it leads me to believe that the fault may be with **hu/index.bdic** but as someone who is unfamiliar with hunspell, I am unable to tell if it should be the Expected string.
If so, it seems more useful to report it here than just fix it at my end.

**Comment by wooorm** [comment]
I’m having an issue with magyarispell, as raised here: https://github.com/laszlonemeth/magyarispell/issues/9. May be related to that.

**Comment by heydojo** [comment]
My guess was character encoding but it's a wild one and I'm completely unfamiliar with hunspell.
Hopefully it's an easy fix.

**Comment by wooorm** [comment]
Should be fixed in https://github.com/wooorm/dictionaries/commit/7e24cd4cb59760fa32c565cc7509da38b3c89fcf and released in https://github.com/wooorm/dictionaries/commit/0e1e08e3f599c9bd570a80945e42295817369245!
