### ISSUE TITLE
dictionnary-fr issue

### ISSUE THREAD

**Issue by revolunet** [wooorm/dictionaries#16]
Hi there ! 

Looks like the suggest/correct methods doesnt handle some words in french, like "préavis"

in index.dic we can find : `préavis po:nom is:mas is:inv`

but `console.log(spell.correct("preavis"));` returns false.

Any idea how to fix this ?

**Comment by revolunet** [comment]
tell me if theres any way we can help :)

**Comment by wooorm** [comment]
Released `dictionary-fr` with a hopefully working version. Could you check that this one works?

**Comment by revolunet** [comment]
Awesome that fix it. Thanks @wooorm 🙏
