### ISSUE TITLE
de_DE: Add greater list of words

### ISSUE THREAD

**Issue by tukusejssirs** [wooorm/dictionaries#18]
Could you extend the German dictionaries with those in in here: [de_dicts.zip](https://github.com/wooorm/dictionaries/files/4527809/de_dicts.zip)? They are all in HunSpell format, but I have never created nor modified these dictionaries.

Note that the archive contains three subfolders:
- `1901`: so called _Old Rules_;
- `1996`: so called _1996 Reform`_;
- `2006`: so called _2006 Reform`_.

Currently, the [`de/index.dic`](https://raw.githubusercontent.com/wooorm/dictionaries/master/dictionaries/de/index.dic) contains 75,767 words only, whereas the `2006/de_DE.dic` contains 163,202 words.

**Comment by wooorm** [comment]
Hey! Dictionaries are crawled from other sources:

https://github.com/wooorm/dictionaries/blob/5ede45bb705d3f9f525ea779f7b487f9fc062013/script/crawl.sh#L240-L242

https://github.com/wooorm/dictionaries/blob/5ede45bb705d3f9f525ea779f7b487f9fc062013/script/crawl.sh#L448-L451

https://github.com/wooorm/dictionaries/blob/5ede45bb705d3f9f525ea779f7b487f9fc062013/script/crawl.sh#L559-L570

I’m not interested in maintaining dictionaries here: this project is to bring them all together. If there is an alternative source to crawl from, that could work.

**Comment by wooorm** [comment]
Closing this, but do let me know if you have an alternative source.
