### ISSUE TITLE
sk: Improve the Slovak dictionary

### ISSUE THREAD

**Issue by tukusejssirs** [wooorm/dictionaries#19]
I have [tried](https://gitlab.com/tukusejssirs/skdict/-/tree/master) to create a dictionary that would contain all (most) Slovak words including all their forms, but I have failed as I have never done it yet.

[Slovak Academy of Sciences (Slovenska akademia vied, SAV)](sav.sk) has worked on a morphology analyser untill approx 2015, which contains 100 MB data. Each word has a flag what part of speech the word is and what grammer case the word is in.

Some links (all in Slovak; if needed, I can translate them for you into English):
- latest version of the morphology analyser: [`ma-2015-02-05.txt.xz`](http://korpus.sk/attachments/morphology_database/ma-2015-02-05.txt.xz);
- [MA information](https://slovnik.juls.savba.sk/ma_info.html);
- [MA database](http://korpus.sk/morphology_database.html);
- [explanations](http://korpus.sk/morpho.html).

I could help you with the translation of the Slovak texts, Slovak grammer and testing.

**Comment by wooorm** [comment]
Cool, I’m all up for making dictionaries better!

Answer is the same as https://github.com/wooorm/dictionaries/issues/18#issuecomment-618905188: I have no knowledge or interest to maintain dictionaries here.

**Comment by wooorm** [comment]
Closing this, but do let me know if you have an alternative source.
