### ISSUE TITLE
Mixed up .dic & .aff files

### ISSUE THREAD

**Issue by Thomas101** [wooorm/dictionaries#2]
Hi, it looks like some of the dictionaries have had the dic and aff files mixed up. Looking through `crawl.sh` the `generate` method calls do look incorrect. Was wondering if this is on purpose or a typo. The affected dictionaries are...

* bulgarian
* czech
* galician
* greek
* russian
* turkish
* ukrainian
* vietnamese

**Comment by wooorm** [comment]
Oh funky! Thanks for finding this!

As you already found the solution, would you be interested in opebing/working on a PR for this?
