### ISSUE TITLE
British spelling of 'onwards'

### ISSUE THREAD

**Issue by Frederick888** [wooorm/dictionaries#21]
According to https://dictionary.cambridge.org/dictionary/english/onwards, 'onwards' is more common in British English, however:

https://github.com/wooorm/dictionaries/blob/4099de3374bc8f0fabaeddbbffbc7ba75c1a96c6/dictionaries/en-GB/index.dic#L34383

And actually it's got 'afterwards':

https://github.com/wooorm/dictionaries/blob/4099de3374bc8f0fabaeddbbffbc7ba75c1a96c6/dictionaries/en-GB/index.dic#L11251

...so I guess it's better to make them consistent?

**Comment by wooorm** [comment]
This project groups dictionaries, but doesn’t maintain them. `en-GB` comes from https://github.com/en-wl/wordlist, so questions and suggestions should go there!
