### ISSUE TITLE
Issues in en-GB dictionary

### ISSUE THREAD

**Issue by StephenRajC** [wooorm/dictionaries#22]
We are facing issue in “en-GB” dictionary, there we couldn’t find the word “**ability**” in aff file. So, the issue occurs all the words related to the word “ability” in suffix. So, can you please provide the definition for that or any other alternative solutions.

**Comment by wooorm** [comment]
This project compiles many dictionaries from many sources. Qs can go to the original sources.

Furthermore: affixes are not words.
