### ISSUE TITLE
Using the dictionary-hu throwing error.

### ISSUE THREAD

**Issue by dskesavan** [wooorm/dictionaries#27]
**Code:**
var dictionary = require('dictionary-hu')
var nspell = require('nspell')
dictionary(ondictionary)
function ondictionary(err, dict) {
    if (err) {
        throw err
    }
    var spell = nspell(dict)
    console.log(spell.correct('Szerelem'))
}

**Error:**
C:\Program Files\nodejs\node.exe .\test.js
Process exited with code 3221225477

**Comment by wooorm** [comment]
You’re probably running out of memory. Set the `--max-old-space-size=SIZE` flag when running Node: https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes

**Comment by wooorm** [comment]
This is also probably more an issue for `nspell`
