### ISSUE TITLE
New Czech dictionary

### ISSUE THREAD

**Issue by SargonCZ** [wooorm/dictionaries#31]
There is a new dictionary for Czech language available, with a lot of corrections made. More about it is written in a [blogpost](http://www.translatoblog.cz/hunspell/) (in czech), the [zip file](https://github.com/wooorm/dictionaries/files/6521542/hunspell_cs.zip) can be directly downloaded here.

Could you include this new dictionary into the project?

**Comment by wooorm** [comment]
Cooool! Awesome to see!

The website seems a bit broken to me, a couple of images don’t load?

Are you maintaining this? Is it backed by a linguistic organization?

Could this dictionary be managed on GH, or another open or specific place? Assuming this will update once in a while, and I’m managing a lot of dictionaries here, it’s quite hard for me to go through websites in languages I don’t speak to look for the latest link!

**Comment by SargonCZ** [comment]
I am not the maintainer, just a user. 

There was a problem with the Czech dictionary - it was full of mistakes and not updated for about 10 years. The author of the website is a translator of subtitles, and he finally got fed up and made a lot of corrections, when he had time during the covid lockdown. However, I don't expect he will work on the dictionary further. 

You can just update the dictionary and when something new get's published in Czech, I will let you know.

**Comment by wooorm** [comment]
Could you elaborate on the status of https://gitlab.com/strepon/czech-cc0-dictionaries/?
Is that still very much work in progress, or might it actually be quite good?

---

> However, I don't expect he will work on the dictionary further.

His last paragraph of the blog post seems to indicate that he welcomes bug reports?

> You can just update the dictionary and when something new get's published in Czech, I will let you know.

I appreciate that, but I’ve also been long enough in open source to know that folks often don’t stick around for years. I want to prevent placing all the work on you.

Could Miroslav Pošta perhaps be persuaded to publish a page on their website dedicated to the dictionary?
Or, as there last paragraph seems to be open to collaboration, to place it in a repo somewhere?

**Comment by SargonCZ** [comment]
> I appreciate that, but I’ve also been long enough in open source to know that folks often don’t stick around for years. I want to prevent placing all the work on you.

You are probably right. I will contact mr. Pošta and try to persuade him to place the work on github or other repositroy.

Yes, he is open for bug reports. I will contact him

**Comment by wooorm** [comment]
Awesome, thank you!

**Comment by wooorm** [comment]
@SargonCZ Heard anything back? Let me know if there’s anything I can help with

**Comment by SargonCZ** [comment]
Sorry, no response as of yet.

**Comment by wooorm** [comment]
Hi again! I’m working on adding it anyway, and the plan is to once in a while search through that website to find for new “hunspell” updates.

Looking at the new dictionary, I immediately noticed that the `TRY` on the 3d line in the `.aff` is incorrect (this seems to be a `KEY` instead)?
