### ISSUE TITLE
Swedish dictionary not working

### ISSUE THREAD

**Issue by undergroundwires** [wooorm/dictionaries#35]
Hi,
Thanks for this easy to use awesome library!
I've been using English dictionary without issues but Swedish dictionary at `dictionary-sv` does not detect any issues but sees any input as correct.
I looked at `index.js` and it looks same as the one for English so I cannot detect the problemhere and appreciate any help.

**Comment by wooorm** [comment]
Hey. This either has to do with the tool you are using or the upstream. More info is needed to debug, but it‘s most likely external.

**Comment by undergroundwires** [comment]
Hi @wooorm , you are right. I thought everyone was having the same issue. I use it using `nspell` from you by loading it like this:

```javascript

import nspell from 'nspell';
import englishLoader from 'dictionary-en';
import swedishLoader from 'dictionary-sv';

async function loadSpellCheckerAsync(lang) {
    const builtInDict = await loadBuiltInDictionaryAsync(lang);
    const spellChecker = new nspell(builtInDict);
    return spellChecker;
}

function loadBuiltInDictionaryAsync(lang) {
    const dictionaryLoader = getDictionaryLoader(lang);
    return new Promise((resolve, reject) => {
        dictionaryLoader((err, dict) => {
            if (err) { reject(err); }
            resolve(dict);
        });
    });
}

function getDictionaryLoader(lang){
    switch(lang) {
        case "en":
            return englishLoader;
        case "sv":
            return swedishLoader;
        default:
            throw new Error(`Unsupported lang: ${lang}`);
    }
}
```

I call `loadSpellCheckerAsync` with `en` and `sv`. English loader works just fine and `.correct` responds to my tokens, however swedish loader assumes everything is always correct.

**Comment by undergroundwires** [comment]
Hi @wooorm , you are right. Thanks for your response and maintaining this awesome suite. It's simple and easy, the best library  in JS ecosystem, and I've tested many.

Sorry for not giving too much context, I thought everyone was having the same issue. I use it using `nspell` from you by loading it like this:

```javascript

import nspell from 'nspell';
import englishLoader from 'dictionary-en';
import swedishLoader from 'dictionary-sv';

async function loadSpellCheckerAsync(lang) {
    const builtInDict = await loadBuiltInDictionaryAsync(lang);
    const spellChecker = new nspell(builtInDict);
    return spellChecker;
}

function loadBuiltInDictionaryAsync(lang) {
    const dictionaryLoader = getDictionaryLoader(lang);
    return new Promise((resolve, reject) => {
        dictionaryLoader((err, dict) => {
            if (err) { reject(err); }
            resolve(dict);
        });
    });
}

function getDictionaryLoader(lang){
    switch(lang) {
        case "en":
            return englishLoader;
        case "sv":
            return swedishLoader;
        default:
            throw new Error(`Unsupported lang: ${lang}`);
    }
}
```

I call `loadSpellCheckerAsync` with `en` and `sv`. English loader works just fine and `.correct` responds to my tokens, however swedish loader assumes everything is always correct.
