### ISSUE TITLE
dictionary-fr words format

### ISSUE THREAD

**Issue by mmouterde** [wooorm/dictionaries#4]
Hello,
I got some trouble with the french dictionary, most of invariable words are not correctly checked.
I openned the dic file and find lines like : 

~~~
voici	89
~~~

I did not found any documentation about this syntax ?! In dictionnary-en there is no digits after words ?!

**Comment by mmouterde** [comment]
https://search.maven.org/remotecontent?filepath=org/languagetool/language-fr/3.8/language-fr-3.8-sources.jar

seems to contain a valid format : no more digits ?!

**Comment by wooorm** [comment]
What are you using to check spelling?

Background: digits as flags are a feature of hunspell. Some dictionaries use one character, some two, and some use numbers.

**Comment by mmouterde** [comment]
I'm using nspell.

Thanks for background. Unfortunately, any words (all ?) with these flags seems to not be recognized...

see http://code.runnable.com/WYAx6t8S4W8OpTKm/dictionary-fr-for-node-js-and-hello-world

**Comment by wooorm** [comment]
Your code now works as expected:

`example.js`:

```js
var dictionary = require('dictionary-fr');
var nspell = require('nspell');

dictionary(function (err, dict) {
  if (err) {
    throw err;
  }

  var spell = nspell(dict);

  console.log(spell.correct('chevaux'));
  console.log(spell.correct('voici'));
});
```

`node example` yields:

```
true
true
```

**Comment by wooorm** [comment]
P.S. I’m not sure what was going on. The tabs seem to be the problem? Anyway, the commit referenced above has some more info!

Thanks for reporting this!

**Comment by mmouterde** [comment]
I confirm, that is fixed. thanks !
