### ISSUE TITLE
Convert to ESM

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/dictionaries#42]
Because 5f2b26a81d108061d565ba49a414182b08e473e4 introduced breaking changes, I think now would be the right time to convert to ESM.

**Comment by wooorm** [comment]
What does that commit break?
All these packages are used a lot in electron, and by folks who have no clue about Node.js/JavaScript, so im delaying this project

**Comment by wooorm** [comment]
Compared to the ESM problem, which is definitely a major

**Comment by remcohaszing** [comment]
If electron support is really important, but old Node.js version support isn't, then never mind this issue 🙂

**Comment by wooorm** [comment]
A lot of folks are getting these dictionaries by manually downloading them and placing the files somewhere. They often don’t know about Node, npm, or JavaScript.
