### ISSUE TITLE
Add words to German dictionary

### ISSUE THREAD

**Issue by mu88** [wooorm/dictionaries#43]
Hey 👋🏻 As you suggested, we should continue our conversation here on GitHub.

__Disclaimer:__ I have almost no clue how Hunspell works, so please forgive if it is a thumb question.

I'm using [ReSpeller](https://www.jetbrains.com/help/resharper/Spell_Checking.html) together with ReSharper in Visual Studio. The German phrase _Zahlung gelöscht_ gets marked as misspelled, so I thought about adding these words to the German Hunspell dictionary.

In [your README](https://github.com/wooorm/dictionaries/tree/main/dictionaries/de#dictionary-de) I found that the source for the German dictionary is [j3e](https://www.j3e.de/ispell/igerman98/index.html). On his page there is a little [online spell checker](https://www.j3e.de/cgi-bin/spellchecker) and when entering my sentence _Zahlung gelöscht_, the result is:  
```
Spellcheck result:

no errors found
```

And now I'm confused: within the [German dictionary](https://raw.githubusercontent.com/wooorm/dictionaries/main/dictionaries/de/index.dic) I don't find the word _Zahlung_, but I do find _gelöscht_:
- So am I encountering a ReSpeller bug regarding _gelöscht_?
- And what about _Zahlung_?
- And why does the online spell checker not complain at all?

I'd really appreciate your feedback!

**Comment by mu88** [comment]
Thank you @fabiospampinato ! And what would you recommend? From your lines I get the impression that this could be an issue of ReSpeller instead of Hunspell, right? Should I get in contact with JetBrains?

**Comment by fabiospampinato** [comment]
> And what would you recommend? 

I'd try to find a version of hunspell that works for what you need, other spell checkers that use the same dictionaries may be buggy.

> From our lines I get the impression that this could be an issue of ReSpeller instead of Hunspell, right? Should I get in contact with JetBrains?

If I had to guess I'd say ReSpeller has some bugs, and it might be worth mentioning this to JetBrains, I'm not certain though 🤷‍♂️

**Comment by mu88** [comment]
Okay, I'll contact JetBrains and update this issue as soon as there are updates
