### ISSUE TITLE
en_GB doesn't work for "misspelt"

### ISSUE THREAD

**Issue by aetinx** [wooorm/dictionaries#44]
The en_GB doesn't work for the word "misspelt", but it does work for "misspelled" (which is wrong according to Grammarly).

<img width="292" alt="image" src="https://user-images.githubusercontent.com/65425469/157235604-3427c63e-0a10-489c-9ee8-76130386df79.png">

<img width="312" alt="image" src="https://user-images.githubusercontent.com/65425469/157235666-cf917b76-9043-41a4-b849-32f201e28057.png">

<img width="188" alt="image" src="https://user-images.githubusercontent.com/65425469/157235727-d380abd0-0d57-44f8-b976-56304b8a5237.png">

**Comment by wooorm** [comment]
This project groups dictionaries together, it’s not where things are maintained. See the sources mentioned for each dictionary.
