### ISSUE TITLE
Investigate shipping `.dic`, `.aff` as JSON

### ISSUE THREAD

**Issue by wooorm** [wooorm/dictionaries#49]
Problem:

* Uses Node-specific APIs, so doesn’t work in browsers, Deno
* Ships a weird callback load function, would be nicer to use the module system to do that

Solution:

- Either as files with an import assertion. Weird shipping a whole string as a single thing in a `.json` file (`"1mb of data"`) *and* also as the normal file (`1mb of data`)?
  ```js
  export {default as aff} from './index.aff.json' assert {type: 'json'}
  export {default as dic} from './index.dic.json' assert {type: 'json'}
  export const dictionary = {aff, dic}
  export {dictionary as default}
  ```
- Potentially even inline? Needs a flag currently in Node, or also an import assertion https://twitter.com/wooorm/status/1513958664884920323. URLs might be limited so dictionaries won’t fit. Might be slow. Might be fast?
  ```js
  export {default as aff} from 'data:application/json,"..."' assert {type: 'json'}
  export {default as dic} from 'data:application/json,"..."' assert {type: 'json'}
  export const dictionary = {aff, dic}
  export {dictionary as default}
  ```

However, that means:

* Breaks CJS (they could still read the files themselves tho)
* Import assertions are very new, so won’t work in a bunch of places

**Comment by fabiospampinato** [comment]
Personally I don't see the benefit of this, is there a tool that can consume them in JSON form? If there is then I guess importing them in JSON might be a little nicer 🤔, in environments that support that. I don't know if it's worth the confusion of shipping all dictionaries in two different formats though.

**Comment by wooorm** [comment]
It is not to ship JSON. It is to ship large plain text in JavaScript. JavaScript only supports JS/JSON/WASM.

**Comment by wooorm** [comment]
Came up with an alternative: use WASM: https://nodejs.org/api/esm.html#wasm-modules.
It currently needs `node --experimental-wasm-modules`, when that is no longer needed, we can encode the files as WASM (basically same size) with this draft code: https://github.com/wooorm/dictionaries/commit/351a9c26b2595f151532d97abe5d6d883d30b2d8.
