### ISSUE TITLE
Not clear about the sources

### ISSUE THREAD

**Issue by EvanCarroll** [wooorm/dictionaries#5]
I think this may be a lot of redundant work. I'm just not clear about the sources, this is a large collection of dictionaries. I was looking for something like this. This project seems to source from [https://extensions.openoffice.org/en/project/polish-dictionary-pack](https://extensions.openoffice.org/en/project/polish-dictionary-pack). But, those were last edited in 08'.

[LibreOffice replaces those dictionaries](https://github.com/LibreOffice/dictionaries). It's another large repository of hunspell. Makes more sense to just that -- [that's what I'm doing for my project.](https://github.com/EvanCarroll/pg_hunspell) It seems like you have similar aims. Would make more sense just to nuke this and pull in from it.

Maybe there is an advantage, be glad to know it.

**Comment by wooorm** [comment]
This sounds pretty dickish... This is free open source software: you can use it or not. I spend my free time on this for fun, and I don’t like my work being called redundant.

Anything I can help with?
