### ISSUE TITLE
[Question] Is there some index accross dictionaries ?

### ISSUE THREAD

**Issue by bacloud22** [wooorm/dictionaries#50]
I want to build a very simple translator using dictionaries, my concerned languages are English, French and Arabic.
Imagine the following dictionaries:

French 
[bourgeois, brunette, contraire, ]

English
[bourgeois, brunette, contrary, ]

If there is an index between the meaning of terms than I can map words easily.

Thanks a lot !

**Comment by wooorm** [comment]
No, there is no index.
These dictionaries contain code to figure out whether a word is valid or not. There is no "meaning" of words
