### ISSUE TITLE
Simple code is not running

### ISSUE THREAD

**Issue by adsonvinicius** [wooorm/dictionaries#51]
I'm trying this package but the console message is never shown

const nspell = require('nspell')
const dictionaryPt = require('dictionary-pt')

```
function testSpell(txt){
    dictionaryPt((error, pt) => {
        if (error) throw error
        var spell = nspell(pt)
        console.log(spell.suggest(txt))
      })
}

testSpell("Maquina")
```

**dictionary-pt: "^3.1.0",
nspell: "^2.1.5"**

I checked the programs stucks at  `var spell = nspell(pt)` line. Any idea what's wrong?

**Comment by fabiospampinato** [comment]
Portuguese might be one of those languages with tens/hundreds of millions of valid words (according to the dictionary anyway), maybe nspell is stuck at processing those 🤔 It'd be useful to profile this

**Comment by adsonvinicius** [comment]
Has anyone has used portuguese dicitonary on _nspell_?

**Comment by hchiam** [comment]
Keep in mind that this repo was last updated 8 months ago in November 2022. 
It might be because `fs.readFile` isn't working from within `node_modules` in the browser. 
I got it working by manually copying the `index.aff` and `index.dic` file and using the following js: 
```js
load();
async function load() {
  const aff = await fetch("./index.aff").then((response) => {
    return response.text();
  });
  const dic = await fetch("./index.dic").then((response) => {
    return response.text();
  });
  const spell = nspell(aff, dic);
  console.log(spell.suggest("teh"));
}
``` 
which outputs the following in the console:
```js
[
  "ten",
  "eh",
  "meh",
  "tea",
  "tech",
  "ted",
  "tee",
  "tel",
  "the",
  "NEH",
  "Te",
  "Tet",
  "Tex",
  "Th"
]
```

**Comment by wooorm** [comment]
Highly unlikely to be related to this project, but related to nspell or the folks making the portuguese dictionary.
