### ISSUE TITLE
Force accents in Russian dictionary (ё)

### ISSUE THREAD

**Issue by artginzburg** [wooorm/dictionaries#53]
Do we have a way to use 'ё' instead of 'е' for [`ru`](https://github.com/wooorm/dictionaries/tree/main/dictionaries/ru) where needed? E.g. 'актер', which is currently in the .dic file, should not be valid in accent-sensitive (case-sensitive) mode. It should be 'актёр'. I see that Portuguese has this issue figured out.

**Comment by artginzburg** [comment]
Looks like Google is not going to fix it. We can really just replace the relevant words by their accented versions after fetching from Google.

**Comment by wooorm** [comment]
Dictionaries are not maintained here. You can report problems and fixes upstream
