### ISSUE TITLE
Lithuanian dictionary is wrong

### ISSUE THREAD

**Issue by mobileFX** [wooorm/dictionaries#54]
Nice work, thank you for maintaining this repo. Lithuanian dictionary seems to be non UTF-8 encoded and gives errors. For example "Tęsti Žaidimą" which means "Continue Game" when checking each word gives errors for every word.

**Comment by wooorm** [comment]
Hi! Everything we get is from a remote source, in this case: https://github.com/ispell-lt/ispell-lt.
That does look somewhat maintained.
But ispell is a very old project, from way before hunspell.
Perhaps, as you seem lithuanian, you can ask them what the correct hunspell data is. And confirm whether that has the same problems or not.

**Comment by mobileFX** [comment]
FYI, opening the original ispell dictionary files in VSCode and using codepage Windows 1257 (Baltic) seems to load them OK. When building the UTF-8 version with the scripts provided something goes wrong.
