### ISSUE TITLE
Use a newer, updated source for Russian

### ISSUE THREAD

**Issue by homocomputeris** [wooorm/dictionaries#55]
The current source for Russian dictionaries was updated long time ago and seems to be unmaintained anymore.

[Arch Linux AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hunspell-ru-aot) ships a newer, updated version from the [Libre Office extension](https://extensions.libreoffice.org/en/extensions/show/russian-dictionary-pack).

It would be great to use those dictionaries here too.

**Comment by wooorm** [comment]
It would be nice if you could get the communities to contribute somewhere that uses Git. Libre Office is a tough place to crawl. Something like github/gitlab/etc is easier. Do you think you could ask folks?

**Comment by homocomputeris** [comment]
This seems to be the source for that extension:
https://cgit.freedesktop.org/libreoffice/dictionaries/tree/ru_RU

**Comment by wooorm** [comment]
I also find https://forumooo.ru/index.php?topic=106.135. Still, it would be rather nice if the community could maintain a dictionary in github/gitlab/etc. Do you think you could ask folks?

**Comment by homocomputeris** [comment]
Will this do?
https://github.com/LibreOffice/dictionaries/tree/master/ru_RU

**Comment by yurtpage** [comment]
There is a new recreated dictionary https://github.com/Goudron/ru-spelling-dictionary
https://habr.com/ru/articles/1043982/
But it has less records than existing.

@Goudron could you add to your dictionary to this repo and to the LibreOffice?
