### ISSUE TITLE
Issue in Dictionary file - Different style apostrophes, it marks it as a misspelling

### ISSUE THREAD

**Issue by Suriya-Murugan** [wooorm/dictionaries#58]
We are having apostrophes difference for browser and word insert.

The top picture was the way the document was opened. You can see all these properly spelled words are marked incorrect because the apostrophe, but once I delete the apostrophe and type it back in, they are correct. " ’ " vs " ' "
Word insert:

![image](https://github.com/wooorm/dictionaries/assets/43063728/3c6948f6-f4bc-431b-82d4-437123a32177)

Browser insert:

![image](https://github.com/wooorm/dictionaries/assets/43063728/c6bd8374-a9a6-4305-af2f-0adff4e0335a)

![image](https://github.com/wooorm/dictionaries/assets/43063728/e978d69d-98b5-4e7a-a10f-e663d1ebc9de)

We have attached the affix 
[en_US.zip](https://github.com/wooorm/dictionaries/files/12536640/en_US.zip)
file

**Comment by wooorm** [comment]
Not enough info.

This project hosts dictionaries, but you send dictionaries? Do you mean they are different from what’s here?

If they *are* from here, they aren’t maintained here. Take it up with the folks that maintain en-us.

Or, take it up with the folks that maintain your spell checker. Lots of dictionaries have this “problem”. Several spell checkers solve it automatically.

**Comment by wooorm** [comment]
Talk to the folks making the dictionary or the ones making your software. This project basically only hosts existing code.
