### ISSUE TITLE
Add Swahili dictionaries

### ISSUE THREAD

**Issue by sommerluk** [wooorm/dictionaries#59]
Hello there, and thanks for the work!

Would it be possible to add also Swahili dictionaries?

LibreOffice provides Hunspell dictionaries for Kenyan Swahili and Tanzanian Swahili:

https://extensions.libreoffice.org/en/extensions/show/swahili-dictionary

There are more places that provide these dictionaries, but I suppose they all have the same content:

https://addons.mozilla.org/en-US/firefox/addon/kiswahili-spell-checker/

https://cgit.freedesktop.org/libreoffice/dictionaries/tree/sw_TZ

https://github.com/elastic/hunspell/tree/master/dicts/sw

Best regards

**Comment by wooorm** [comment]
Hey, thanks for your patience!

I looked at them, unfortunately they are low quality.
They are just a giant list of words.

Hunspell dictionaries like this are slow and buggy. Good hunspell dictionaries are supposed to have an `.aff` file with rules, and then the `.dic` file uses those rules.

If a good quality dictionary exists, I’d of course add it :)
