### ISSUE TITLE
There should be no Eszett in Swiss German

### ISSUE THREAD

**Issue by Certary** [wooorm/dictionaries#60]
The Swiss German (de-CH) dictionaries should not include Eszett (`ß`) characters. In Swiss German this special character is replaced by `ss` as described [here](https://en.wikipedia.org/wiki/Swiss_Standard_German#Written_Swiss_Standard_German).

**Comment by wooorm** [comment]
dictionaries are not maintained here

**Comment by eliakocher** [comment]
@wooorm what do you mean they are not maintained? the de-CH dictionary is completely wrong. It's not generated from the correct source.

**Comment by wooorm** [comment]
then fix that thanks
