### ISSUE TITLE
Find words

### ISSUE THREAD

**Issue by Sammeeey** [wooorm/dictionaries#64]
Can I use this library to generate a list of word of certain type - e.g. get all nouns, then all verbs, then all conjuctions, then all adjectives, ...?
Or is its only pupose the spell checking (presented in the example inside the readme)?

**Comment by wooorm** [comment]
Dictionaries are for spell checking. Depending on the dictionaries, which are not maintained here, there might be annotations to words. See hunspell for what you can do with morphological info.
