### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by YoannBuzenet** [wooorm/dictionaries#68]
Hello, 

Thank you for this lib.

I'm trying to make it work on a test repo.

This code throws :

```
import en from "dictionary-en";

console.log(en);
```

With the following error : 

```
yoann@yoann-XPS-ubuntu:~/dev/test$ ts-node dictionnary/index.ts 
/home/yoann/.nvm/versions/node/v20.12.0/lib/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/yoann/dev/test/node_modules/dictionary-en/index.js from /home/yoann/dev/test/dictionnary/index.ts not supported.
Instead change the require of index.js in /home/yoann/dev/test/dictionnary/index.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/home/yoann/.nvm/versions/node/v20.12.0/lib/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/home/yoann/dev/test/dictionnary/index.ts:7:41)
    at m._compile (/home/yoann/.nvm/versions/node/v20.12.0/lib/node_modules/ts-node/dist/index.js:857:29) {
  code: 'ERR_REQUIRE_ESM'
```

I checked the index.js file in node_modules, as you can see it does not hold require() call : 

```
/**
 * @typedef Dictionary
 *   Hunspell dictionary.
 * @property {Uint8Array} aff
 *   Data for the affix file (defines the language, keyboard, flags, and more).
 * @property {Uint8Array} dic
 *   Data for the dictionary file (contains words and flags applying to those words).
 */

import fs from 'node:fs/promises'

const aff = await fs.readFile(new URL('index.aff', import.meta.url))
const dic = await fs.readFile(new URL('index.dic', import.meta.url))

/** @type {Dictionary} */
const dictionary = {aff, dic}

export default dictionary
```

I'm on node 20.12.0

Would you have any idea of what I could do to make it work ?

**Comment by YoannBuzenet** [comment]
I'm ready to help with a PR, I just don't know how to approach the problem. I've read some docs but this ESM/commonJS thing (+ ts-node which interacts above it) - it seems to deep haha - which I why I'd be curious to solve it. 
If you have any idea, happy to help and dig

**Comment by wooorm** [comment]
Hey! This package uses ESM. I am not interested in adding CJS again.
Either use ESM yourself, or use the previous version (which was CJS).

I personally recommend adding `"type": "module"` to your `package.json`, then you’re in ESM. I’ve done that for about 4 years now. Works well in 100s of projects.

**Comment by YoannBuzenet** [comment]
It works with `npx tsx dictionnary/index.ts`
but node with ts-node

I can't even get the file being executed with esm config with ts-node, I don't know where it comes from

I'll just go with tsx
Thank you
