### ISSUE TITLE
Shouldn't the dictionnary-en/index.js be in typescript ?

### ISSUE THREAD

**Issue by YoannBuzenet** [wooorm/dictionaries#69]
Hey, I gave some thoughts about the ESM error and I wanted to ask you:

The file cannot be compiled by typescript because it is a .js file with a .d .ts aside

therefore we're stuck in ESM
If we want to use the tsc tool to go to CJS if needed (for example in an existing repo stuck on it), we cannot. It would work if it was in typescript directly

If we write them in `.ts` and export them in `.js` to not break compatibility with exiting repo, you would allow CJS export without breaking current imports. We can build in CI before publishing to registry, therefore you wouldn't have to look at it anymroe afterwards.

What do you think? Your library compatible with both environments
I'd be happy to help

**Comment by wooorm** [comment]
hey again!

No, it shouldn’t.

TypeScript is a) a language, b) a compiler.

I don‘t use the language. I just use JavaScript. I do use the TypeScript compiler.

All of this is unrelated to ESM vs CJS.

I maintain 100s of projects, which are used billions of times. They are typed. They do not use the TypeScript language. They worked 4 years ago in CJS. Now they are ESM. They work.

**Comment by YoannBuzenet** [comment]
> All of this is unrelated to ESM vs CJS.
The TS compiler allows CJS compatibility, how can that be unrelated ? Maybe I don't get it, but to me it's directly related?

> They work.
Yes, for codebase full ESM. Not for those stuck in CJS that must use an old version.

I don't want to fight, thank you for your work, I'll just rewrite it in ts and make it work in my CJS oriented TS project.

I don't know if it was a "get out" answer or not, I'd be happy to have your answer about this, but I feel like I won't. Have a good day

**Comment by wooorm** [comment]
You could. You could also do that with plain JavaScript.

> Yes, for codebase full ESM. Not for those stuck in CJS that must use an old version.

That is intentional. Quoting from my earlier answer in https://github.com/wooorm/dictionaries/issues/68#issuecomment-2242568845:

> This package uses ESM. I am not interested in adding CJS again.
> Either use ESM yourself, or use the previous version (which was CJS).
