### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins

### ISSUE THREAD

**Issue by DharmikDpatel** [wooorm/dictionaries#70]
Getting error when building my react application. I have just imported "dictionary-en" and tried to build application but giving error. Need help in order to find a solution or a workaround to resolve this issue.

Node version: 20.9.0

Below is my code:
SpellCheck.js

import en from "dictionary-en";
const SpellCheck = () => {
  console.log(en);
};
export default SpellCheck;

![Screenshot 2024-07-29 104447](https://github.com/user-attachments/assets/51751f58-7809-4d75-adad-759d6d62a5db)

**Comment by wooorm** [comment]
The error indicates you use a too old version of Node. Update your things

**Comment by DharmikDpatel** [comment]
Hi Sir, I am using Node JS LTM verison 20.16.0 and I feel it should work here. What minimum version should I have to run this package? This answer will help me to use this package in more efficient way.

**Comment by wooorm** [comment]
Then it’s not Node, but something else that you use that fails. I don‘t know what you use. Look into your other build tools.

**Comment by wooorm** [comment]
No
